#! /bin/sh

# Autostart Apps
sxhkd &
compton -b
mpd && mpc clear && mpc add /
~/Scripts/startup
devilspie &
wal -i ~/Pictures/alto1.png -b 0d111c
tmux new zsh &

# Backup Wallpaper
#wal -i ~/Pictures/shinobu.jpg -b 0d111c
#hsetroot -full ~/Pictures/shinobu.jpg

# BSPWM Workspace
bspc monitor -d I II III IV V VI VII VIII IX

# Gaps
bspc config border_width         0
bspc cpnfig top_padding          0
bspc cpnfig bottom_padding       0
bspc cpnfig left_padding         0
bspc cpnfig right_padding        0
bspc config window_gap           12

# Border colors
#bspc config normal_border_color "#484848"
#bspc config focused_border_color "#3441c9"
#bspc config urgent_border_color "#B58900"
#bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# First Workspace
bspc rule -a Firefox desktop='^1' focus=on follow=on
bspc rule -a Places desktop='^1' state=floating focus=on follow=on
bspc rule -a St desktop='^2' focus=on follow=on
bspc rule -a Pcmanfm desktop='^3' focus=on follow=on
bspc rule -a code-oss desktop='^4' focus=on follow=on
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a scrcpy desktop='^5' follow=on
bspc rule -a dotnet desktop='^6' follow=on
bspc rule -a vlc desktop='^6' follow=on
bspc rule -a Lxappearance desktop='^7' state=floating follow=on
bspc rule -a XTerm state=floating focus=on follow=on
bspc rule -a Viewnior state=floating focus=on follow=on
bspc rule -a Screenkey manage=off
