#!/bin/sh

### AUTOSTART ###

sxhkd &
compton -b &
mpd && mpc clear && mpc add /
~/Scripts/startup &
devilspie &
wal -i ~/Pictures/Alto/alto1.png -b 0d111c
xsetroot -cursor_name left_ptr

### BACKUP ###

#wal -i ~/Pictures/shinobu.jpg -b 0d111c
#hsetroot -full ~/Pictures/shinobu.jpg
#urxvtd -q &

### BSPWM CONFIGS ###
bspc config monitor -d 1 2 3 4 5 6 7 8 9

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#3441c9"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config border_width             0
bspc config top_padding              20
bspc config bottom_padding           0
bspc config left_padding             0
bspc config right_padding            0
bspc config window_gap               12

bspc config split_ratio              0.50
bspc config borderless_monocle       true
bspc config gapless_monocle          false
bspc config focus_follows_pointer    true

### WINDOW RULES ###

#-----------Class-Name--------------------Workspaces---Focus----Follow------State-------#
bspc rule -a firefox                     desktop='^1' focus=on follow=on
bspc rule -a St                          desktop='^2' focus=on follow=on
bspc rule -a Pcmanfm                     desktop='^3' focus=on follow=on
bspc rule -a code-oss                    desktop='^4' focus=on follow=on
bspc rule -a Emacs                       desktop='^4' focus=on follow=on state=tiled
bspc rule -a Gimp                        desktop='^5'          follow=on
bspc rule -a scrcpy                      desktop='^5'          follow=on
bspc rule -a dotnet                      desktop='^6'          follow=on
bspc rule -a Vlc                         desktop='^6'          follow=on
bspc rule -a Lxappearance                desktop='^7'          follow=on state=floating
bspc rule -a java-lang-Thread            desktop='^7'                    state=floating
bspc rule -a Manjaro\ Settings\ Manager  desktop='^7' focus=on follow=on
bspc rule -a stacer                                   focus=on follow=on state=floating
bspc rule -a music                                    focus=on follow=on state=floating
bspc rule -a Viewnior                                 focus=on follow=on state=floating
bspc rule -a Screenkey                   manage=off
#---------------------------------------------------------------------------------------#
